accounts/urls.py
from django.urls import path,include
from . import views

app_name = "accounts_app"

urlpatterns = [
    path("", views.accounts, name="accounts_page"),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("store.urls", namespace="store_app")),
    path("account/", include("accounts.urls", namespace="accounts_app")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path,include
from . import views

app_name = "store_app"

urlpatterns = [
    path("", views.store, name="store_page"),

    path("cart/", views.cart, name="cart_page"),

    path("checkout/", views.checkout, name="checkout_page"),

    path("update_item/", views.update_item, name="update_item_page"),

    path("process_order/", views.process_order, name="process_order_page"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

store/models.py
from django.db import models
from accounts.models import User
# from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.db.models.fields import NullBooleanField
from django.db.models.query_utils import check_rel_lookup_compatibility

# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True)
    mobile_number = models.CharField(max_length=15)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100, null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=False)
    product_image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.product_image.url
        except:
            url = ""
        return url


class Order(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True
    )
    date_orderd = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderItems = self.orderitem_set.all()
        for item in orderItems:
            if item.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderItems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderItems])
        return total

    @property
    def get_cart_items(self):
        orderItems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderItems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, blank=True, null=True
    )
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=100, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

accounts/views.py
from django.shortcuts import render

# Create your views here.

def accounts(request):
    context = { }
    return render(request, "accounts/accounts.html", context)

store/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import JsonResponse
from django.forms.models import model_to_dict
from .models import *
from .utils import cartData

# Create your views here.


def store(request):
    data = cartData(request)
    # print(data)

    items = data["items"]
    order = data["orders"]
    cartItems = data["cartItems"]

    products = Product.objects.all()
    context = {
        "products": products,
        "items": items,
        "orders": order,
        "cartItems": cartItems,
    }
    return render(request, "store/store.html", context)


def cart(request):
    context = {}
    return render(request, "store/store.html", context)


def checkout(request):
    context = {}
    return render(request, "store/store.html", context)


def update_item(request):
    context = {}
    return render(request, "store/store.html", context)


def process_order(request):
    context = {}
    return render(request, "store/store.html", context)

accounts/templates/accounts/accounts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>this is accounts page</h1>
</body>
</html>

store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="{% url 'store_app:store_page' %}">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{orders.get_cart_items}}</strong></h5></th>
						<th><h5>Total:<strong> Rs:{{orders.get_cart_total}}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'store_app:checkout_page' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in items %}

				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>Rs:{{item.product.price}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product= "{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
					
							<img data-product= "{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>{{item.get_total}}</p></div>
				</div>
				{% endfor %}

			</div>
		</div>
	</div>
{% endblock content %}

store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<div class="row">
	<div class="col-lg-6">
		<div class="box-element" id="form-wrapper">
			<form id="form" method="POST" novalidate >
				
				<div id="user-info">
					<div class="form-field">
						<input required class="form-control" type="text" name="name" placeholder="Name..">
					</div>
					<div class="form-field">
						<input required class="form-control" type="email" name="email" placeholder="Email..">
					</div>
				</div>

				<div id="shipping-info">
					<hr>
					<p>Shipping Information:</p>
					<hr>
					<div class="form-field">
						<input class="form-control" type="text" name="address" placeholder="Address..">
					</div>
					<div class="form-field">
						<input class="form-control" type="text" name="city" placeholder="City..">
					</div>
					<div class="form-field">
						<input class="form-control" type="text" name="state" placeholder="State..">
					</div>
					<div class="form-field">
						<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
					</div>
					<div class="form-field">
						<input class="form-control" type="text" name="country" placeholder="country..">
					</div>
				</div>

				<hr>
				<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
			</form>
		</div>

		<br>
		<div class="box-element hidden" id="payment-info">
			<small>Paypal Options</small>
			<!-- <button id="make-payment">make payment</button> -->
			<div id="paypal-button-container"></div>
		</div>

	</div>

	<div class="col-lg-6">
		<div class="box-element">
			<a class="btn btn-outline-dark" href="{% url 'store_app:cart_page' %}">&#x2190; Back to Cart</a>
			<hr>
			<h3>Order Summary</h3>
			<hr>
			{% for item in items %}
			<div class="cart-row">              
				<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
				<div style="flex:2">
					<p>{{item.product.name}}</p>
				</div>
				<div style="flex:1">
					<p>{{item.product.price}}</p>
				</div>
				<div style="flex:1">
					<p> x {{item.quantity}} </p>
				</div>
			</div>
			{% endfor %}
			<h5>Items:{{orders.get_cart_items}}</h5>
			<h5>Total:Rs {{orders.get_cart_total}}</h5>
		</div>
	</div>
</div>


<script src="https://www.paypal.com/sdk/js?client-id=AW8yELQzHRh24hfsDhmh03Aru4eJUVBJXdHlYXlWP1df6turuQosqO-RLem0MdoAXa_K_qlzZyWOXTtA&currency=USD&disable-funding=credit"></script>

<script>

	var total ='{{orders.get_cart_total}}'
	// Render the PayPal button into #paypal-button-container
	paypal.Buttons({

		style :{
			color: 'blue',
			shape: 'rect',
		},

		// Set up the transaction
		createOrder: function(data, actions) {
			return actions.order.create({
				purchase_units: [{
					amount: {
						value: parseFloat(total).toFixed(2)
					}
				}]
			});
		},

		// Finalize the transaction
		onApprove: function(data, actions) {
			return actions.order.capture().then(function(details) {
				// Show a success message to the buyer
				submitFormData()
			});
		}


	}).render('#paypal-button-container');
</script>


<script type="text/javascript">
	var shipping = "{{orders.shipping}}"
	var cartTotal = '{{orders.get_cart_total}}'
	if (shipping == 'False') {
		document.getElementById('shipping-info').innerHTML = ' '
	}

	if (user != 'AnonymousUser') {
		document.getElementById('user-info').classList.add('hidden')
	}

	if (shipping == 'False' && user != 'AnonymousUser') {
		document.getElementById("form-wrapper").classList.add('hidden')
		document.getElementById("payment-info").classList.remove('hidden')
	}


	var form = document.getElementById('form')
	form.addEventListener('submit', function (e) {
		e.preventDefault()
		console.log('form submitted ......')
		document.getElementById('form-button').classList.add('hidden')
		document.getElementById('payment-info').classList.remove('hidden')

	})

	// document.getElementById("make-payment").addEventListener('click', function (e) {
	// 	submitFormData()
	// })



	function submitFormData() {
		console.log("payment button clicked ")

		var userInfo = {
			'name': null,
			'email': null,
			'cartTotal': cartTotal
		}

		var shippingInfo = {
			'address': null,
			'city': null,
			'state': null,
			'zipcode': null,
			'country': null,
		}
		console.log('shippin into is ', shippingInfo, 'user info is:', userInfo)

		if (shipping != 'False') {

			shippingInfo.address = form.address.value
			shippingInfo.city = form.city.value
			shippingInfo.state = form.state.value
			shippingInfo.zipcode = form.zipcode.value
			shippingInfo.country = form.country.value

		}

		if (user == 'AnonymousUser'){
			userInfo.name = form.name.value
			userInfo.email = form.email.value
		}

		var url = "/process_order/"

		fetch( url, {
			method:"POST",
			headers: {
				"Content-Type": 'application/json',
				"X-CSRFToken": csrftoken,
			},
			body: JSON.stringify({
				"userInfo": userInfo,
				"shippingInfo": shippingInfo
			})
		})

		.then( response => {
			return response.json()
		})

		.then( data => {
			console.log('success.... ', data)
			alert('Transaction Completed')

			cart = {}
			document.cookie = "cart=" + JSON.stringify(cart) + ";domain;path=/"

			window.location.href = "{% url 'store_app:store_page' %}"
		})
		
	}



</script>


{% endblock content %}

store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>Ecom</title>
	<link rel="shortcut icon" href="#">

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
		integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	
	<script type="text/javascript">
		var user = '{{request.user}}';
		var csrftoken = "{{csrf_token}}";
		console.log("value of token is ", csrftoken)


		// function getCookie(name) {
		// 	// split cookie String and ger all individual name = value pairs in an array  
		// 	var cookieArr = document.cookie.split(";")
		// 	// loop through array elements 
		// 	for (var i = 0; i < cookieArr.length; i++) {
		// 		var cookiePair = cookieArr[i].split("=")
		// 		// removing white space at the beginning of teh cookie name
		// 		// and compare it with the given string 
		// 		if (name == cookiePair[0].trim()) {
		// 			// decode the cookie value ad return
		// 			return decodeURIComponent(cookiePair[i]);
		// 		}
		// 	}
		// 	// return null if not found
		// 	return null;
		// }
		// var cart = JSON.parse( getCookie('cart') );
		// JSON.parse(JSON.stringify(error))
		// if (cart == undefined) {
		// 	cart = {}
		// 	console.log('cart was created')
		// 	document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
		// }

		// console.log('cart:', cart)

	</script>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="{% url 'store_app:store_page' %}">Ecom</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'store_app:store_page' %}">Store <span class="sr-only">(current)</span></a>
				</li>

			</ul>
			<div class="form-inline my-2 my-lg-0">
				<a href="#" class="btn btn-warning">Login</a>

				<a href="{% url 'store_app:cart_page' %}">
					<img id="cart-icon" src="{% static 'images/cart.png' %}">
				</a>
				<p id="cart-total">{{cartItems}}</p>

			</div>
		</div>
	</nav>

	<div class="container">
		<br>
		{% block content %}


		{% endblock content %}
	</div>


	<script>


	</script>


	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
		integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
		crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
		integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
		crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
		integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
		crossorigin="anonymous"></script>

	<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.js"
		integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
</body>

</html>

store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
	<div class="row">

		{% for product in products %}
		<div class="col-lg-4">
			<img class="thumbnail" src="{{product.imageURL}}" id="image">
			<div class="box-element product">
				<h6><strong id="product_name">{{product.name}}</strong></h6>
				<hr>
				<!-- adding custom attributes  -->
				<button data-product = "{{product.id}}" data-action = "add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
				<a class="btn btn-outline-success" href="#">View</a>
				<h4 style="display: inline-block; float: right"><strong>Rs:{{product.price}}</strong></h4>

			</div>
		</div>
		{% endfor %}
	</div>

{% endblock content %}